tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "on-tertiary-fixed-variant": "#733600",
                    "on-error-container": "#93000a",
                    "surface": "#f3faff",
                    "on-surface-variant": "#414752",
                    "on-surface": "#071e27",
                    "primary-fixed": "#d4e3ff",
                    "outline-variant": "#c1c6d4",
                    "secondary": "#4c616c",
                    "error": "#ba1a1a",
                    "on-secondary-container": "#526772",
                    "tertiary-container": "#ba5b00",
                    "surface-container": "#dbf1fe",
                    "error-container": "#ffdad6",
                    "on-primary-fixed-variant": "#004786",
                    "surface-tint": "#005faf",
                    "primary": "#005dac",
                    "on-primary-fixed": "#001c3a",
                    "surface-container-high": "#d5ecf8",
                    "on-tertiary": "#ffffff",
                    "surface-variant": "#cfe6f2",
                    "secondary-container": "#cfe6f2",
                    "on-secondary": "#ffffff",
                    "surface-container-lowest": "#ffffff",
                    "outline": "#717783",
                    "on-secondary-fixed": "#071e27",
                    "on-secondary-fixed-variant": "#354a53",
                    "inverse-surface": "#1e333c",
                    "secondary-fixed-dim": "#b4cad6",
                    "primary-fixed-dim": "#a5c8ff",
                    "surface-bright": "#f3faff",
                    "on-tertiary-fixed": "#311300",
                    "on-primary-container": "#fffdff",
                    "tertiary": "#944700",
                    "surface-container-low": "#e6f6ff",
                    "primary-container": "#1976d2",
                    "on-background": "#071e27",
                    "on-tertiary-container": "#fffeff",
                    "surface-container-highest": "#cfe6f2",
                    "on-primary": "#ffffff",
                    "surface-dim": "#c7dde9",
                    "secondary-fixed": "#cfe6f2",
                    "on-error": "#ffffff",
                    "inverse-primary": "#a5c8ff",
                    "background": "#f3faff",
                    "inverse-on-surface": "#dff4ff",
                    "tertiary-fixed-dim": "#ffb688",
                    "tertiary-fixed": "#ffdbc7"
            },
            "borderRadius": {
                    "DEFAULT": "0.125rem",
                    "lg": "0.25rem",
                    "xl": "0.5rem",
                    "full": "0.75rem"
            },
            "fontFamily": {
                    "headline": ["Manrope"],
                    "display": ["Manrope"],
                    "body": ["Inter"],
                    "label": ["Inter"]
            }
          },
        },
      }
